"""Metaprogrammed table-route factory.

One call to :func:`register_table_routes` registers the full GET/POST × format
matrix (6 routes) for a table-shaped resource — the records table and every
feature table share this exact shape. The caller supplies endpoint builders
(``make_get_endpoint`` / ``make_post_endpoint``) that capture the
:class:`DataResponseFormat` by closure and declare the FastAPI-visible
signature (path params + injected dependencies), because path params differ
between resources (``/{schema}/records`` vs ``/{schema}/{feature}``).

Operation IDs are stable and match the OpenAPI contract:
``{resource}_{method}_{format_key}`` where ``format_key`` is ``json`` / ``csv``
/ ``csv_gz``.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

from fastapi import APIRouter

from osa.application.api.v1.routes.data.formats import FORMATS, DataResponseFormat

EndpointBuilder = Callable[[DataResponseFormat], Callable[..., Any]]


def format_key(fmt: DataResponseFormat) -> str:
    """``""`` → ``json``; ``csv`` → ``csv``; ``csv.gz`` → ``csv_gz``."""
    return "json" if fmt.suffix == "" else fmt.suffix.replace(".", "_")


def _existing_operation_ids(router: APIRouter) -> set[str]:
    """Operation IDs already registered on *router* (from prior factory calls)."""
    return {op for r in router.routes if (op := getattr(r, "operation_id", None))}


def path_for(base_path: str, fmt: DataResponseFormat) -> str:
    return base_path if fmt.suffix == "" else f"{base_path}.{fmt.suffix}"


def register_table_routes(
    router: APIRouter,
    base_path: str,
    make_get_endpoint: EndpointBuilder,
    make_post_endpoint: EndpointBuilder,
    resource_name: str,
) -> None:
    """Register GET + POST routes for every format under ``base_path``.

    Formats are registered longest-suffix-first so the bare (JSON) path is added
    last. This matters when ``base_path`` ends in a path parameter (e.g. the
    feature table's ``/{schema}/{feature}``): Starlette's ``{feature}`` matches
    ``[^/]+``, which includes dots, so a bare ``/{schema}/{feature}`` registered
    first would greedily capture ``feature.csv.gz`` as the feature name and the
    suffixed routes would never match. Resources with a literal segment (records)
    are unaffected by the ordering.
    """
    # Seed with op IDs already on this router so a second factory call for a
    # different resource (records + feature share one router) can't silently mint
    # a colliding id — operation IDs must be globally unique for SDK codegen.
    seen_ids = _existing_operation_ids(router)
    for fmt in sorted(FORMATS, key=lambda f: len(f.suffix), reverse=True):
        key = format_key(fmt)
        path = path_for(base_path, fmt)
        get_id = f"{resource_name}_get_{key}"
        post_id = f"{resource_name}_post_{key}"
        for op_id in (get_id, post_id):
            if op_id in seen_ids:
                raise ValueError(
                    f"Duplicate operation_id generated by the table factory: {op_id!r}. "
                    f"Resource name {resource_name!r} collides with a route already on this "
                    "router — operation IDs must be globally unique for SDK codegen."
                )
            seen_ids.add(op_id)
        router.add_api_route(
            path,
            make_get_endpoint(fmt),
            methods=["GET"],
            operation_id=get_id,
            response_model=None,
        )
        router.add_api_route(
            path,
            make_post_endpoint(fmt),
            methods=["POST"],
            operation_id=post_id,
            response_model=None,
        )
