"""hook registry, releases, runs; convention slug; feature run_id (#145)

Revision ID: 67e4e4a1a045
Revises: 076_feature_fks
Create Date: 2026-06-14 18:56:34.263585

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "67e4e4a1a045"
down_revision: Union[str, Sequence[str], None] = "076_feature_fks"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hooks",
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("feature_spec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("live_release_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "hook_releases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("hook_name", sa.String(length=40), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("image", sa.Text(), nullable=False),
        sa.Column("digest", sa.Text(), nullable=False),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("limits", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_ref", sa.Text(), nullable=False),
        sa.Column("built_by", sa.Text(), nullable=True),
        sa.Column("built_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["hook_name"],
            ["hooks.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hook_name", "digest", name="uq_hook_releases_hook_digest"),
        sa.UniqueConstraint("hook_name", "version", name="uq_hook_releases_hook_version"),
    )
    op.create_index(
        "idx_hook_releases_hook_version",
        "hook_releases",
        ["hook_name", sa.literal_column("version DESC")],
        unique=False,
    )
    op.create_table(
        "hook_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("release_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_s", sa.Float(), nullable=False),
        sa.Column("oom_retries", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("log_ref", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["hook_releases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_hook_runs_release", "hook_runs", ["release_id"], unique=False)
    # Conventions: slug-keyed identity replaces the opaque SRN PK (#145).
    op.add_column("conventions", sa.Column("id", sa.String(), nullable=False))
    op.drop_constraint("conventions_pkey", "conventions", type_="primary")
    op.drop_column("conventions", "srn")
    op.create_primary_key("conventions_pkey", "conventions", ["id"])
    op.add_column("depositions", sa.Column("convention_id", sa.String(), nullable=False))
    op.drop_column("depositions", "convention_srn")
    op.add_column("ingest_runs", sa.Column("convention_id", sa.String(), nullable=False))
    op.drop_index(op.f("idx_ingest_runs_convention"), table_name="ingest_runs")
    op.create_index("idx_ingest_runs_convention", "ingest_runs", ["convention_id"], unique=False)
    op.drop_column("ingest_runs", "convention_srn")
    op.add_column("records", sa.Column("convention_id", sa.Text(), nullable=False))
    op.drop_index(op.f("idx_records_convention_srn"), table_name="records")
    op.create_index("idx_records_convention_id", "records", ["convention_id"], unique=False)
    op.drop_column("records", "convention_srn")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "records", sa.Column("convention_srn", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.drop_index("idx_records_convention_id", table_name="records")
    op.create_index(op.f("idx_records_convention_srn"), "records", ["convention_srn"], unique=False)
    op.drop_column("records", "convention_id")
    op.add_column(
        "ingest_runs",
        sa.Column("convention_srn", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_index("idx_ingest_runs_convention", table_name="ingest_runs")
    op.create_index(
        op.f("idx_ingest_runs_convention"), "ingest_runs", ["convention_srn"], unique=False
    )
    op.drop_column("ingest_runs", "convention_id")
    op.add_column(
        "depositions",
        sa.Column("convention_srn", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("depositions", "convention_id")
    op.add_column(
        "conventions", sa.Column("srn", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_constraint("conventions_pkey", "conventions", type_="primary")
    op.drop_column("conventions", "id")
    op.create_primary_key("conventions_pkey", "conventions", ["srn"])
    op.drop_index("idx_hook_runs_release", table_name="hook_runs")
    op.drop_table("hook_runs")
    op.drop_index("idx_hook_releases_hook_version", table_name="hook_releases")
    op.drop_table("hook_releases")
    op.drop_table("hooks")
    # ### end Alembic commands ###
