"""initial schema

Revision ID: c6d9f4c0c3ab
Revises:
Create Date: 2026-06-14 19:29:44.101012

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c6d9f4c0c3ab"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Per-schema metadata projection tables (metadata.*) are created at runtime,
    # but the metadata_store does NOT create their PG schema — do it here.
    op.execute('CREATE SCHEMA IF NOT EXISTS "metadata"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conventions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("schema_id", sa.String(), nullable=False),
        sa.Column("schema_version", sa.String(), nullable=False),
        sa.Column("file_requirements", sa.JSON(), nullable=False),
        sa.Column("hooks", sa.JSON(), nullable=False),
        sa.Column("source", sa.JSON(), nullable=True),
        sa.Column("docs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("trace_context", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_events_type_created",
        "events",
        ["event_type", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "feature_tables",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("hook_name", sa.String(), nullable=False),
        sa.Column("pg_table", sa.String(), nullable=False),
        sa.Column("feature_schema", sa.JSON(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hook_name", name="uq_feature_tables_hook_name"),
    )
    op.create_table(
        "hooks",
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("feature_spec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("live_release_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "ingest_runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("convention_id", sa.String(), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column(
            "ingestion_finished", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("batches_ingested", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("batches_completed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("published_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("batch_size", sa.Integer(), server_default=sa.text("1000"), nullable=False),
        sa.Column("record_limit", sa.Integer(), nullable=True),
        sa.Column("batches_failed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("failure_kind", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_ingest_runs_convention", "ingest_runs", ["convention_id"], unique=False)
    op.create_index("idx_ingest_runs_status", "ingest_runs", ["status"], unique=False)
    op.create_table(
        "metadata_tables",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("schema_id", sa.Text(), nullable=False),
        sa.Column("schema_slug", sa.Text(), nullable=False),
        sa.Column("schema_major", sa.Integer(), nullable=False),
        sa.Column("schema_versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("pg_table", sa.Text(), nullable=False),
        sa.Column("metadata_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pg_table", name="uq_metadata_tables_pg_table"),
        sa.UniqueConstraint("schema_id", "schema_major", name="uq_metadata_tables_id_major"),
    )
    op.create_table(
        "ontologies",
        sa.Column("srn", sa.String(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("srn"),
    )
    op.create_table(
        "records",
        sa.Column("srn", sa.String(), nullable=False),
        sa.Column("convention_id", sa.Text(), nullable=False),
        sa.Column("schema_id", sa.Text(), nullable=False),
        sa.Column("schema_version", sa.Text(), nullable=False),
        sa.Column("source", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("srn"),
    )
    op.create_index("idx_records_convention_id", "records", ["convention_id"], unique=False)
    op.create_index(
        "idx_records_metadata_gin",
        "records",
        ["metadata"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"metadata": "jsonb_path_ops"},
    )
    op.create_index("idx_records_published_at", "records", ["published_at"], unique=False)
    op.create_index("idx_records_schema_id", "records", ["schema_id"], unique=False)
    op.create_index(
        "uq_records_source",
        "records",
        [sa.literal_column("(source ->> 'type')"), sa.literal_column("(source ->> 'id')")],
        unique=True,
    )
    op.create_table(
        "schemas",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("fields", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", "version"),
    )
    op.create_index("idx_schemas_id", "schemas", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "validation_runs",
        sa.Column("srn", sa.String(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("results", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("srn"),
    )
    op.create_index(
        "idx_validation_runs_expires_at", "validation_runs", ["expires_at"], unique=False
    )
    op.create_table(
        "deliveries",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("consumer_group", sa.String(length=128), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivery_error", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("deliver_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "consumer_group", name="uq_delivery_event_consumer"),
    )
    op.create_index(
        "idx_deliveries_claim",
        "deliveries",
        ["consumer_group", "status", "event_id"],
        unique=False,
        postgresql_where=sa.text("status IN ('pending', 'claimed')"),
    )
    op.create_index(
        "idx_deliveries_deliver_after",
        "deliveries",
        ["deliver_after"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_index("idx_deliveries_event", "deliveries", ["event_id"], unique=False)
    op.create_index(
        "idx_deliveries_failed",
        "deliveries",
        ["consumer_group", "retry_count"],
        unique=False,
        postgresql_where=sa.text("status = 'failed'"),
    )
    op.create_index(
        "idx_deliveries_stale",
        "deliveries",
        ["claimed_at"],
        unique=False,
        postgresql_where=sa.text("status = 'claimed'"),
    )
    op.create_table(
        "depositions",
        sa.Column("srn", sa.String(), nullable=False),
        sa.Column("convention_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("files", sa.JSON(), nullable=False),
        sa.Column("record_id", sa.String(), nullable=True),
        sa.Column("owner_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("srn"),
    )
    op.create_index("idx_depositions_owner_id", "depositions", ["owner_id"], unique=False)
    op.create_index("idx_depositions_record_id", "depositions", ["record_id"], unique=False)
    op.create_table(
        "device_authorizations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("device_code", sa.String(length=64), nullable=False),
        sa.Column("user_code", sa.String(length=8), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_code", name="uq_device_auth_device_code"),
        sa.UniqueConstraint("user_code", name="uq_device_auth_user_code"),
    )
    op.create_index(
        "ix_device_auth_status_expires",
        "device_authorizations",
        ["status", "expires_at"],
        unique=False,
    )
    op.create_table(
        "hook_releases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("hook_name", sa.String(length=40), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("image", sa.Text(), nullable=False),
        sa.Column("digest", sa.Text(), nullable=False),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("limits", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_ref", sa.Text(), nullable=False),
        sa.Column("built_by", sa.Text(), nullable=True),
        sa.Column("built_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["hook_name"],
            ["hooks.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hook_name", "digest", name="uq_hook_releases_hook_digest"),
        sa.UniqueConstraint("hook_name", "version", name="uq_hook_releases_hook_version"),
    )
    op.create_index(
        "idx_hook_releases_hook_version",
        "hook_releases",
        ["hook_name", sa.literal_column("version DESC")],
        unique=False,
    )
    # Live-pointer FK, added after both tables exist to break the circular
    # hooks.live_release_id ↔ hook_releases.hook_name dependency. DEFERRABLE so
    # the release-insert-then-pointer-update happens in one transaction.
    op.create_foreign_key(
        "fk_hooks_live_release_id",
        "hooks",
        "hook_releases",
        ["live_release_id"],
        ["id"],
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_table(
        "identities",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "external_id", name="uq_identity_provider_external"),
    )
    op.create_index("ix_identities_user_id", "identities", ["user_id"], unique=False)
    op.create_table(
        "ontology_terms",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("ontology_srn", sa.String(), nullable=False),
        sa.Column("term_id", sa.String(length=255), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("synonyms", sa.JSON(), nullable=False),
        sa.Column("parent_ids", sa.JSON(), nullable=False),
        sa.Column("definition", sa.Text(), nullable=True),
        sa.Column("deprecated", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["ontology_srn"], ["ontologies.srn"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ontology_srn", "term_id", name="uq_ontology_term"),
    )
    op.create_index(
        "idx_ontology_terms_ontology_srn", "ontology_terms", ["ontology_srn"], unique=False
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_refresh_tokens_family_id", "refresh_tokens", ["family_id"], unique=False)
    op.create_index("ix_refresh_tokens_token_hash", "refresh_tokens", ["token_hash"], unique=False)
    op.create_index("ix_refresh_tokens_user_id", "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "role_assignments",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("assigned_by", sa.String(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "role", name="uq_role_assignments_user_role"),
    )
    op.create_index("ix_role_assignments_user_id", "role_assignments", ["user_id"], unique=False)
    op.create_table(
        "hook_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("release_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_s", sa.Float(), nullable=False),
        sa.Column("oom_retries", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("log_ref", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["hook_releases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_hook_runs_release", "hook_runs", ["release_id"], unique=False)
    op.create_table(
        "instance_statistics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("storage_bytes", sa.BigInteger(), nullable=False),
        sa.Column("feature_rows", sa.BigInteger(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the live-pointer FK first so hook_releases can be dropped below.
    op.drop_constraint("fk_hooks_live_release_id", "hooks", type_="foreignkey")
    op.drop_table("instance_statistics")
    op.drop_index("idx_hook_runs_release", table_name="hook_runs")
    op.drop_table("hook_runs")
    op.drop_index("ix_role_assignments_user_id", table_name="role_assignments")
    op.drop_table("role_assignments")
    op.drop_index("ix_refresh_tokens_user_id", table_name="refresh_tokens")
    op.drop_index("ix_refresh_tokens_token_hash", table_name="refresh_tokens")
    op.drop_index("ix_refresh_tokens_family_id", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index("idx_ontology_terms_ontology_srn", table_name="ontology_terms")
    op.drop_table("ontology_terms")
    op.drop_index("ix_identities_user_id", table_name="identities")
    op.drop_table("identities")
    op.drop_index("idx_hook_releases_hook_version", table_name="hook_releases")
    op.drop_table("hook_releases")
    op.drop_index("ix_device_auth_status_expires", table_name="device_authorizations")
    op.drop_table("device_authorizations")
    op.drop_index("idx_depositions_record_id", table_name="depositions")
    op.drop_index("idx_depositions_owner_id", table_name="depositions")
    op.drop_table("depositions")
    op.drop_index(
        "idx_deliveries_stale",
        table_name="deliveries",
        postgresql_where=sa.text("status = 'claimed'"),
    )
    op.drop_index(
        "idx_deliveries_failed",
        table_name="deliveries",
        postgresql_where=sa.text("status = 'failed'"),
    )
    op.drop_index("idx_deliveries_event", table_name="deliveries")
    op.drop_index(
        "idx_deliveries_deliver_after",
        table_name="deliveries",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index(
        "idx_deliveries_claim",
        table_name="deliveries",
        postgresql_where=sa.text("status IN ('pending', 'claimed')"),
    )
    op.drop_table("deliveries")
    op.drop_index("idx_validation_runs_expires_at", table_name="validation_runs")
    op.drop_table("validation_runs")
    op.drop_table("users")
    op.drop_index("idx_schemas_id", table_name="schemas")
    op.drop_table("schemas")
    op.drop_index("uq_records_source", table_name="records")
    op.drop_index("idx_records_schema_id", table_name="records")
    op.drop_index("idx_records_published_at", table_name="records")
    op.drop_index(
        "idx_records_metadata_gin",
        table_name="records",
        postgresql_using="gin",
        postgresql_ops={"metadata": "jsonb_path_ops"},
    )
    op.drop_index("idx_records_convention_id", table_name="records")
    op.drop_table("records")
    op.drop_table("ontologies")
    op.drop_table("metadata_tables")
    op.drop_index("idx_ingest_runs_status", table_name="ingest_runs")
    op.drop_index("idx_ingest_runs_convention", table_name="ingest_runs")
    op.drop_table("ingest_runs")
    op.drop_table("hooks")
    op.drop_table("feature_tables")
    op.drop_index("idx_events_type_created", table_name="events")
    op.drop_table("events")
    op.drop_table("conventions")
    # ### end Alembic commands ###
    op.execute('DROP SCHEMA IF EXISTS "metadata" CASCADE')
